#!/bin/bash

: << LICENCA
/*
* Script para gerar ou descompactar arquivos .tar.gz
* Copyright (C) 2012 Secretaria Municipal da Saúde
* Osório, Rio Grande do Sul, Brasil
* dtisaude@hotmail.com
* Tiago Cardoso Floriano <mail@poweredbycaffeine.com.br>
*
* Este programa e software livre; voce pode redistribui-lo e/ou
* modifica-lo sob os termos da Licenca Publica Geral GNU, conforme
* publicada pela Free Software Foundation; tanto a versao 2 da
* Licenca como (a seu criterio) qualquer versao mais nova.
*
* Este programa e distribuido na expectativa de ser util, mas SEM
* QUALQUER GARANTIA; sem mesmo a garantia implicita de
* COMERCIALIZACAO ou de ADEQUACAO A QUALQUER PROPOSITO EM
* PARTICULAR. Consulte a Licenca Publica Geral GNU para obter mais
* detalhes.
*
* Voce deve ter recebido uma copia da Licenca Publica Geral GNU
* junto com este programa; se nao, escreva para a Free Software
* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
* 02111-1307, USA.
*
* Copia da licenca no diretorio licenca/licenca_en.txt
* licenca/licenca_pt.txt
*/
LICENCA

shopt -s extglob
read -n1 -p "Você deseja [c]ompactar ou [d]escompactar? (c / d) " opcao
echo ""
echo ""
if [[ $opcao == +(d|D) ]]
	then
	echo "Nome do arquivo .tar.gz (sem a extensão): "; read arquivo
	echo ""
	tar -vzxf $arquivo.tar.gz
	echo ""
	echo "Descompactado!";
elif [[ $opcao == +(c|C) ]]
	then
	echo "Informe os arquivos ou pastas para compactar, usando espaço para alternar entre os arquivos: "; read arquivos_para_compactar
	echo ""
	echo "Informe o nome do arquivo .tar.gz a ser gerado (sem a extensão):"; read nome_arquivo
	tar -cf $nome_arquivo.tar $arquivos_para_compactar
	gzip -9 $nome_arquivo.tar
	echo "Compactado com o nome $nome_arquivo.tar.gz!"
else
	echo "Opção inválida!"
fi
echo ""
